# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pandas-0.24.1-python_2.7-on-linux_64, last modified Mon Feb  4 16:22:04 2019
# ------------------------------------------------

package:
    name: pandas
    version: 0.24.1
source:
    sha256: 435821cb2501eabbcee7e83614bd710940dc0cf28b5afbc4bdb816c31cec71af
    url: https://github.com/pandas-dev/pandas/releases/download/v0.24.1/pandas-0.24.1.tar.gz
build:
    number: '0'
    string: py27he6710b0_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_6
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.12.5 0
        - certifi 2018.11.29 py27_0
        - cython 0.29.2 py27he6710b0_0
        - intel-openmp 2019.1 144
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - mkl 2018.0.3 1
        - ncurses 6.1 he6710b0_1
        - numpy 1.12.1 py27h9378851_1
        - openssl 1.1.1a h7b6447c_0
        - pip 18.1 py27_0
        - python 2.7.15 h9bab390_6
        - readline 7.0 h7b6447c_5
        - setuptools 40.6.3 py27_0
        - sqlite 3.26.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.32.3 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.12.1,<2.0a0
        - python >=2.7,<2.8.0a0
        - python-dateutil >=2.5.*
        - pytz
test:
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
